name: contenedores
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Iconos estilo iOS (vienen por defecto)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Reglas de estilo (vienen por defecto)
  flutter_lints: ^4.0.0

# --- AQUÍ EMPIEZA LA CONFIGURACIÓN DE LA IMAGEN ---
flutter:
  uses-material-design: true

  # Para añadir assets (imágenes, fuentes, etc.)
  # La indentación (espacios) es CRUCIAL aquí.
  assets:
    - assets/Suiza-Montañas.jpg